# Generated by Django 4.2 on 2023-04-06 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post_titulo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fechapost',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo_tag',
            field=models.CharField(default='Travel Blog!', max_length=40),
        ),
    ]
